server:

  port: 8083



spring:

  application:

    name: security-access-control



  datasource:

    url: ${DB_URL:jdbc:postgresql://localhost:5432/access_control}

    username: ${DB_USER:access}

    password: ${DB_PASS:access}



  jpa:

    hibernate:

      ddl-auto: validate


    properties:

      hibernate:

        jdbc:

          time_zone: UTC



  flyway:

    enabled: true



  data:

    redis:

      host: ${REDIS_HOST:localhost}

      port: 6379



policy:

  service:

    url: ${POLICY_ENGINE_URL:http://localhost:8084}


management:

 endpoints:

   web:

    exposure:

     include:

      - health

      - info

      - prometheus